### ISSUE TITLE
Ревью #1

### ISSUE THREAD

**Issue by ShkiTTer** [Egor-Ruban/Bubble#1]
1.  `lateinit` переменные штука классная, но очень опасная. В любой момент может оказаться, что она еще не успела проинициализироваться, а ты ее уже вызываешь. Приложение тут же упадет.

К сожалению, проверить на то, что инициализирована никак нельзя. Поэтому лучше использовать вместо `lateinit` `nullable` переменные. Их всегда можно проверить на `null`, а значит ты все контролируешь. 

В данных случаях хорошо бы подошла "ленивая" инициализация - http://developer.alexanderklimov.ru/android/kotlin/lateinit.php#bylazy
https://github.com/Egor-Ruban/Bubble/blob/ae885f74e2c4dc09153b33f1dd21e38a9d898929/app/src/main/java/com/example/bubbles/MainActivity.kt#L21-L24

2.  `220` напрашивается на вынос в константу. Похожих ситуаций ниже еще не мало
https://github.com/Egor-Ruban/Bubble/blob/ae885f74e2c4dc09153b33f1dd21e38a9d898929/app/src/main/java/com/example/bubbles/MainActivity.kt#L40-L41

3. Если использовать "ленивую" инициализацию этот метод просто уйдет за ненадобностью. См. пункт 1
https://github.com/Egor-Ruban/Bubble/blob/ae885f74e2c4dc09153b33f1dd21e38a9d898929/app/src/main/java/com/example/bubbles/MainActivity.kt#L71-L81

4. Если при объявлении переменной сразу указываешь ей значение, то тип можно не указывать
https://github.com/Egor-Ruban/Bubble/blob/ae885f74e2c4dc09153b33f1dd21e38a9d898929/app/src/main/java/com/example/bubbles/Bubble.kt#L19-L27

5. Не понятно зачем каждый раз при вызове метода `move` устанавливать ширину и высоту экрана, которые всегда постоянные.
https://github.com/Egor-Ruban/Bubble/blob/ae885f74e2c4dc09153b33f1dd21e38a9d898929/app/src/main/java/com/example/bubbles/Bubble.kt#L40-L44

6. Логичным выглядит перед стартом новой анимации проверить есть ли предыдущая и если есть, то предварительно ее остановить
https://github.com/Egor-Ruban/Bubble/blob/ae885f74e2c4dc09153b33f1dd21e38a9d898929/app/src/main/java/com/example/bubbles/Bubble.kt#L71-L73

7. `ConstraintLayout` для поля, в котором просто перемещаются вьюшки слишком избыточен. Тут лучше использовать более легкий и простой `FrameLayout`
https://github.com/Egor-Ruban/Bubble/blob/ae885f74e2c4dc09153b33f1dd21e38a9d898929/app/src/main/res/layout/activity_main.xml#L44-L52

За `ViewBinding` лайк. Как и за использование `ViewPropertyAnimator`

**Comment by Egor-Ruban** [comment]
1) поменял на ленивое. Уже и забыл о нём, спасибо

Вроде в этом же уроке, который ты скинул есть инфа про isInitialized(). С ней есть какие-то хитрости или просто не красиво её использовать?
> К сожалению, проверить на то, что инициализирована никак нельзя.

2) Была такая мысль. Почему 220 оставил - не знаю, про остальные решил, что они не достойны того, чтобы уйти в константы. Стоит вообще все однотипные значения в константы выносить?
6) Как проверять это? сходу не нашёл решения, решил просто при любом удобном случае завершать анимацию

**Comment by ShkiTTer** [comment]
1. Да, использовать `initialized` не хорошо.
2. Суть выноса в константы банальная лучшая читаемость кода и немного оптимизация. Гораздо понятнее, когда в коде встречается строка `left - MARGIN_16`, чем `left - 16`. Одно имя константы уже дает понять, что там лежит и для чего сделана эта операция. 

А для оптимизации, потому что когда значение лежит в константе оно инициализируется один раз на все приложение. И сколько бы экземпляров класса не создавалось, значение инициализируется только первый раз.

Смотри. Запись `private var bubbleSize = 220` - это просто переменная. Константы в Kotlin объявляются в `companion object` - https://kotlinlang.org/docs/object-declarations.html#companion-objects

Объявляются они так - `private const val BUBBLE_SIZE = 220`

3. Если для анимации использовать `nullable` тип. Тогда, вся проверка сведется к проверке на `null`. Т.е, если не `null`, то вызываешь метод `cancel` и записываешь в переменную `null`, а дальше уже делаешь новую анимацию. 

Типа такого:
```
if (foo != null) {
   foo?.cancel()
   foo = null
}

foo = view.animate() .....
```

**Comment by Egor-Ruban** [comment]
ну вроде подправил

**Comment by ShkiTTer** [comment]
Да, гуд. На будущее: `companion object` принято писать в начале классе. Если у тебя есть константы, которые используются в нескольких местах, то для них лучше просто завести отдельный файл
